/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_Buddy`; params?: Router.UnknownInputParams; } | { pathname: `/_DemoScreens`; params?: Router.UnknownInputParams; } | { pathname: `/_HomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/_MissionScreens`; params?: Router.UnknownInputParams; } | { pathname: `/_MorningRoutineScreen`; params?: Router.UnknownInputParams; } | { pathname: `/_SettingsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/_SharedUI`; params?: Router.UnknownInputParams; } | { pathname: `/_constants`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_Buddy`; params?: Router.UnknownOutputParams; } | { pathname: `/_DemoScreens`; params?: Router.UnknownOutputParams; } | { pathname: `/_HomeScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/_MissionScreens`; params?: Router.UnknownOutputParams; } | { pathname: `/_MorningRoutineScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/_SettingsScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/_SharedUI`; params?: Router.UnknownOutputParams; } | { pathname: `/_constants`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_Buddy${`?${string}` | `#${string}` | ''}` | `/_DemoScreens${`?${string}` | `#${string}` | ''}` | `/_HomeScreen${`?${string}` | `#${string}` | ''}` | `/_MissionScreens${`?${string}` | `#${string}` | ''}` | `/_MorningRoutineScreen${`?${string}` | `#${string}` | ''}` | `/_SettingsScreen${`?${string}` | `#${string}` | ''}` | `/_SharedUI${`?${string}` | `#${string}` | ''}` | `/_constants${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_Buddy`; params?: Router.UnknownInputParams; } | { pathname: `/_DemoScreens`; params?: Router.UnknownInputParams; } | { pathname: `/_HomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/_MissionScreens`; params?: Router.UnknownInputParams; } | { pathname: `/_MorningRoutineScreen`; params?: Router.UnknownInputParams; } | { pathname: `/_SettingsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/_SharedUI`; params?: Router.UnknownInputParams; } | { pathname: `/_constants`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; };
    }
  }
}
